platforms:
  github:
    enabled: 0
    remote: github
    additionalGitignoreFile: '.cheezmil_quick_git/config/additional-github-gitignore.txt'
    pushRefspec: 'main:main'
    owner: cheezmil
    tokenFilePath: '"D:\MyNotes\pw\github\cheezmil\pw-pat-classic-cheezimil.txt"'
    remoteUrl: 'https://github.com/{owner}/{current_working_directory_name}'
    primary: false
  gitea:
    enabled: 1
    primary: true
    remote: gitea
    additionalGitignoreFile: '.cheezmil_quick_git/config/additional-gitea-gitignore.txt'
    pushRefspec: 'main:main'
    owner: AlexanderDash
    tokenFilePath: 'D:\MyNotes\pw\gitea\pw_gitea.txt'
    remoteUrl: ''
  gitee:
    enabled: 0
    remote: gitee
    additionalGitignoreFile: '.cheezmil_quick_git/config/additional-gitee-gitignore.txt'
    pushRefspec: ''
    owner: ''
    tokenFilePath: ''
    remoteUrl: ''
    primary: false
  gitcode:
    enabled: 0
    remote: gitcode
    additionalGitignoreFile: '.cheezmil_quick_git/config/additional-gitcode-gitignore.txt'
    pushRefspec: ''
    owner: AlexanderDash
    tokenFilePath: 'D:\MyNotes\pw\gitcode\pw-t-AlexanderDash.txt'
    remoteUrl: ''
    primary: false
  atomgit:
    enabled: 0
    remote: atomgit
    additionalGitignoreFile: '.cheezmil_quick_git/config/additional-atomgit-gitignore.txt'
    pushRefspec: ''
    owner: ''
    tokenFilePath: ''
    remoteUrl: ''
    primary: false
settings:
  pushSequentially: 1
  continueOnError: 0
  showSummary: 1
  defaultAdditionalGitignoreFile: '.cheezmil_quick_git/config/additional-gitea-gitignore.txt'
  gitea_remote_protocol: http
  gitea_host: 127.0.0.1
  gitea_http_port: 3000
  gitea_ssh_port: 3001
  gitea_ssh_user: git
  custom_other_version_path: ''
  myOwnNames:
    - AlexanderDash
    - cheezmil
  nestedGitHandling:
    enabled: 1
    scanDepth: 8
    mode: rename
  forceResetFiles:
    - '.cheezmil_quick_git/config/additional-gitea-gitignore.txt'
